// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9tp_DBPxAIINrVdimCLHil5YpS6Y11VM',
    appId: '1:135284625531:web:2537fdd5ca0dc62793d2de',
    messagingSenderId: '135284625531',
    projectId: 'fishnetlk-3d762',
    authDomain: 'fishnetlk-3d762.firebaseapp.com',
    storageBucket: 'fishnetlk-3d762.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAERSLUS4ZjvzB0QOJYFfT_cKdMHzo3Azg',
    appId: '1:135284625531:android:d07c54ed6c038cba93d2de',
    messagingSenderId: '135284625531',
    projectId: 'fishnetlk-3d762',
    storageBucket: 'fishnetlk-3d762.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW0pwlloWW-YPjIqII-UGK2plzyzUGwAw',
    appId: '1:135284625531:ios:69576788ad20ff2993d2de',
    messagingSenderId: '135284625531',
    projectId: 'fishnetlk-3d762',
    storageBucket: 'fishnetlk-3d762.appspot.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBW0pwlloWW-YPjIqII-UGK2plzyzUGwAw',
    appId: '1:135284625531:ios:69576788ad20ff2993d2de',
    messagingSenderId: '135284625531',
    projectId: 'fishnetlk-3d762',
    storageBucket: 'fishnetlk-3d762.appspot.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9tp_DBPxAIINrVdimCLHil5YpS6Y11VM',
    appId: '1:135284625531:web:6e60209903d89c4593d2de',
    messagingSenderId: '135284625531',
    projectId: 'fishnetlk-3d762',
    authDomain: 'fishnetlk-3d762.firebaseapp.com',
    storageBucket: 'fishnetlk-3d762.appspot.com',
  );

}