// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgFmO6xV6yl69x86zcBb5or1R8Kb282sU',
    appId: '1:200178333772:web:cbf5bf23bbe394c3811ce9',
    messagingSenderId: '200178333772',
    projectId: 'fishnetlk-d24cf',
    authDomain: 'fishnetlk-d24cf.firebaseapp.com',
    storageBucket: 'fishnetlk-d24cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAa_fW-_RcW23ERxpk6tDrqgTU_Gc7RprM',
    appId: '1:200178333772:android:025525489c9e380c811ce9',
    messagingSenderId: '200178333772',
    projectId: 'fishnetlk-d24cf',
    storageBucket: 'fishnetlk-d24cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB293J5oTX_GOcXa8VoJA9VjY_wx4admB8',
    appId: '1:200178333772:ios:9db32e644f4e053e811ce9',
    messagingSenderId: '200178333772',
    projectId: 'fishnetlk-d24cf',
    storageBucket: 'fishnetlk-d24cf.appspot.com',
    iosClientId: '200178333772-9hossn25im3vedjidh8fq6k3kb92arba.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB293J5oTX_GOcXa8VoJA9VjY_wx4admB8',
    appId: '1:200178333772:ios:340d6aca86d5b3e8811ce9',
    messagingSenderId: '200178333772',
    projectId: 'fishnetlk-d24cf',
    storageBucket: 'fishnetlk-d24cf.appspot.com',
    iosClientId: '200178333772-m80q49j35j4f77vkdhb9b8aa7ia1fajn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fishnetlk.RunnerTests',
  );
}
