// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAqOmKxwyLxs-vFzamfKrnwWCru2nGDqNQ',
    appId: '1:901372316128:web:a97f676e998be8f3738385',
    messagingSenderId: '901372316128',
    projectId: 'fishnetlk-74358',
    authDomain: 'fishnetlk-74358.firebaseapp.com',
    storageBucket: 'fishnetlk-74358.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0VGdisgZhMNVEGhIffDBk0NKodvaFKoc',
    appId: '1:901372316128:android:1280795e8abd3d2e738385',
    messagingSenderId: '901372316128',
    projectId: 'fishnetlk-74358',
    storageBucket: 'fishnetlk-74358.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAKpzKJ25F1_AqiHzn3P-Kmjn4by2-lIM',
    appId: '1:901372316128:ios:4657a3f7bc1e0575738385',
    messagingSenderId: '901372316128',
    projectId: 'fishnetlk-74358',
    storageBucket: 'fishnetlk-74358.appspot.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAAKpzKJ25F1_AqiHzn3P-Kmjn4by2-lIM',
    appId: '1:901372316128:ios:4657a3f7bc1e0575738385',
    messagingSenderId: '901372316128',
    projectId: 'fishnetlk-74358',
    storageBucket: 'fishnetlk-74358.appspot.com',
    iosBundleId: 'com.example.fishnetlk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAqOmKxwyLxs-vFzamfKrnwWCru2nGDqNQ',
    appId: '1:901372316128:web:6f20a3290e5783f2738385',
    messagingSenderId: '901372316128',
    projectId: 'fishnetlk-74358',
    authDomain: 'fishnetlk-74358.firebaseapp.com',
    storageBucket: 'fishnetlk-74358.appspot.com',
  );

}